apiVersion: v1
kind: Secret
metadata:
  name: pulumi-access-token
type: Opaque
stringData:
  accessToken: <redacted>

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  # public key added to gitlab repo as a deploy key
  sshPrivateKey: |
  <redacted>
---


apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: bug-npm-install
spec:
  accessTokenSecret: pulumi-access-token
  gitAuthSecret: gitlab-secret
  stack: <stack>
  projectRepo: <repo>
  destroyOnFinalize: true
  refresh: true
  commit: master
